# 项目相关配置
jiage:
  # 名称
  name: jiage
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  # demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  # profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  # addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  # captchaType: math

# 开发环境配置
server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

# Swagger配置
swagger:
  # 是否开启Swagger
  enabled: true